export const searchMenus = [
  { title: 'Dashboard', path: '/dashboard' },
  { title: 'Profil Sekolah', path: '/profile/school' },
  { title: 'Jabatan', path: '/entities/positions' },
  { title: 'Rombel / Kelas', path: '/academic/classrooms' },
  { title: 'Tingkat Kelas', path: '/academic/grades' },
  { title: 'Jurusan', path: '/academic/majors' },
  { title: 'Tahun Ajaran', path: '/academic/years' },
  { title: 'Semester', path: '/academic/semesters' },
  { title: 'Siswa & Wali', path: '/entities/students' },
  { title: 'Pegawai / Guru', path: '/entities/employees' },
  { title: 'Mata Pelajaran', path: '/academic/subjects' },
  { title: 'Jam Pelajaran', path: '/academic/class-periods' },
  { title: 'Jadwal Pelajaran', path: '/academic/schedules' },
  { title: 'Kenaikan Kelas', path: '/academic/promotions' },
  { title: 'Kelulusan', path: '/academic/graduations' },
  { title: 'Pengaturan Absensi', path: '/attendance/settings' },
  { title: 'Absensi Siswa', path: '/attendance/students' },
  { title: 'Absensi Pegawai', path: '/attendance/employees' },
  { title: 'Komponen Penilaian', path: '/assessment/components' },
  { title: 'Agenda Penilaian', path: '/assessment/exams' },
  { title: 'Cetak Rapor', path: '/assessment/report-cards' },
  { title: 'Prestasi Siswa', path: '/student-affairs/achievements' },
  { title: 'Pelanggaran (Kasus)', path: '/student-affairs/violations' },
  { title: 'Pengumuman', path: '/announcements' },
  { title: 'Pengguna', path: '/admin/users' },
  { title: 'Peran (Roles)', path: '/admin/roles' },
  { title: 'Pengaturan', path: '/settings' }
];
